version: '2'
services:
  app:
    build: 
        context: ./
        dockerfile: ./app/Dockerfile
    volumes:
      - /notebooks:/notebooks
  proxy:
    build: proxy
    links:
      - app
    ports:
      - 443:443
      - 80:80
    volumes:
      - '/etc/ssl/certs:/etc/ssl/certs'