AWSTemplateFormatVersion: "2010-09-09"

Resources:

  EcsInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: InstancePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Sid: GetBootstrapScripts
                Effect: Allow
                Action: 
                  - ecs:DeregisterContainerInstance
                  - ecs:DiscoverPollEndpoint
                  - ecs:Poll
                  - ecs:RegisterContainerInstance
                  - ecs:StartTelemetrySession
                  - ecs:Submit*
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"
              -
                Sid: CloudwatchLogging
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStream
                Resource:
                  - arn:aws:logs:*:*:*

  EcsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: EcsInstanceRole
  
Outputs:

  EcsInstanceRole:
    Description: Name of EcsInstanceProfile
    Value: !Ref EcsInstanceRole
    Export:
      Name: !Sub ${AWS::StackName}-EcsInstanceProfile
